<%@ Page Title="" Language="C#" MasterPageFile="~/MainTemplate.Master" AutoEventWireup="true" CodeBehind="WebForm11.aspx.cs" Inherits="Lab3.WebForm11" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <br />
    <br />
    <%-- Main container for content DO NOT TOUCH --%>
    <div class="container border border-1 bg-light container-fluid">
        <div class="row">
            <center>
                <br />
                <h2>Library of Analyzed</h2>
            </center>
        </div>
        <div class="align-items-center text-center">
            <asp:GridView ID="AnalyzedStories" AutoGenerateDeleteButton="true" DataKeyNames="ID" Width="100%" RowStyle-CssClass="rows" CssClass="MyGridView" PagerStyle-CssClass="pager" runat="server" AllowPaging="true" HorizontalAlign="Center" BorderStyle="Solid" BorderWidth="5px" GridLines="Both" RowStyle-HorizontalAlign="Center" RowStyle-Height="15px" AutoGenerateColumns="false" OnRowDataBound="AnalyzedStories_RowDataBound" AutoGenerateSelectButton="true" OnSelectedIndexChanged="AnalyzedStories_SelectedIndexChanged" DeleteMethod="AnalyzedStories_DeleteItem"></asp:GridView>
        </div>

    </div>
</asp:Content>
